# Generated by Django 4.2.5 on 2024-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('email', models.TextField()),
            ],
        ),
    ]
