# Generated by Django 5.0.3 on 2024-05-06 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identity', models.CharField(choices=[('本校學生', '本校學生'), ('外校學生', '外校學生'), ('行政人員', '行政人員'), ('臨時人員', '臨時人員')], default='all', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
