# Generated by Django 5.0.3 on 2024-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_user_email_alter_user_password_alter_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistor_name', models.CharField(max_length=100)),
                ('vistor_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
