# Generated by Django 5.0.3 on 2024-07-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='vistor_name',
            new_name='visitor_name',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='vistor_phone',
            new_name='visitor_phone',
        ),
    ]
