# Generated by Django 5.0.3 on 2024-07-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_vistor_name_visitor_visitor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_phone',
            new_name='phone',
        ),
    ]
