# Generated by Django 5.0.3 on 2024-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_visitor_name_visitor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
    ]
