# Generated by Django 5.0.3 on 2024-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_eventrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
