# Generated by Django 5.0.3 on 2024-08-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_yourmodel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user_id',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
