# Generated by Django 5.0.3 on 2024-08-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_visitor_user_id_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user_id',
        ),
    ]
