# Generated by Django 5.0.3 on 2024-08-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_visitor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user_id',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
