# Generated by Django 5.0.6 on 2024-09-18 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_visitor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
