# Generated by Django 5.0.6 on 2024-09-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
