# Generated by Django 5.0.6 on 2024-11-07 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.yourmodel'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
