# Generated by Django 5.0.6 on 2024-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_eventrecord_data_id_remove_visitor_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='data',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='data_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
