# Generated by Django 5.0.6 on 2024-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_eventrecord_data_remove_visitor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='data_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
