# Generated by Django 5.0.6 on 2024-11-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_eventrecord_data_id_alter_visitor_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
